### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by alejosv** [mi-erasmusmc/comap#21]
Excellent project. I'm working from [PAHO](https://www.paho.org/en) in multiples scenarios where this tool could be very util. We are working with dictionaries terminologics like [MedDRA](https://www.meddra.org/), [WhoDrug](https://who-umc.org/whodrug/whodrug-global/), Snomed and ICD but all in spanish.

This project support the use for example of Snomed spanish version?

**Comment by benozol** [comment]
CodeMapper supports natively all vocabularies that are mapped in the UMLS, which includes current releases of the Spanish SOMED-CT and MedDRA. Not sure about WhoDrug and Spanish ICD, though. For a few vocabularies that aren't mapped in the UMLS we also use third-party mappings for integration.

(Also, sorry for the delay: just catching up on the GH notifications…)

**Comment by alejosv** [comment]
Great, thanks
