### ISSUE TITLE
release v2

### ISSUE THREAD

**Issue by benozol** [mi-erasmusmc/comap#24]
- [ ] retain tags on remap
- [ ] retain old codes on remap (as custom codes)
- [ ] prevent new comments on resolved topics
- [ ] distinguish resolved topics visually
- [ ] add search box for vocabularies
- [ ] sort concepts, codes by columns
- [ ] add concepts from descendant codes dialog
- [ ] clarify error message `"cannot run review operation, not saved yet"`

**Comment by Simamohammad** [comment]
I have a suggestion: We should have the capability to filter not only by coding system but also by tags. For instance, there are times when we only want to track the narrow codes, so we should be able to filter by "narrow."

**Comment by Simamohammad** [comment]
We need to replace the current codemapper output columns with the main columns shown below. All of our scripts are configured to use the columns as specified below, and we prefer to maintain consistency across our outputs.

Current Codemapper output : 
![image](https://github.com/mi-erasmusmc/comap/assets/134608008/dae02a44-e1d0-4900-8fa4-f652005252f6)
we prefer this : 
![image](https://github.com/mi-erasmusmc/comap/assets/134608008/3044e062-1352-4c9d-afed-d2d528a9069f)

**Comment by Simamohammad** [comment]
we need to output all the codelist in one CSV file . we have the script ready for this . can we start doing so ?

**Comment by benozol** [comment]
all points copied to https://github.com/VAC4EU/Codemapper/pull/1, to be continued there
